name: build

on:
  push:
    branches-ignore:
    - 'refs/tags/*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Install latest stable
      if: matrix.os == 'macos-latest'
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - uses: actions/checkout@v3
    - name: Cache target directory
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.OS }}-target-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.OS }}-target-${{ github.ref }}-
          ${{ runner.OS }}-target-master-
          ${{ runner.OS }}-target-
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
