name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Cache target directory
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.OS }}-target-${{ github.ref }}
        restore-keys: |
          ${{ runner.OS }}-target-master
          ${{ runner.OS }}-target-
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
