name: upload-release-assets

on:
  release:
    types: [created]

jobs:
  crates:
    name: Upload crate to crates.io
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Publish on crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish

  assets:
    name: Build and upload release assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: windows-latest
          asset_path: target\\release\\totp.exe
          asset_name: totp-windows.exe
        - os: macos-latest
          asset_path: target/release/totp
          asset_name: totp-macos
        - os: ubuntu-latest
          asset_path: target/release/totp
          asset_name: totp-linux

    steps:
    - name: Install latest stable rust toolchain
      if: matrix.os == 'macos-latest'
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - uses: actions/checkout@v1
      name: Checkout code

    - name: Restore cache
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.OS }}-target-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.OS }}-target-${{ github.ref }}-
          ${{ runner.OS }}-target-master-
          ${{ runner.OS }}-target-

    - name: Build release
      run: cargo build --release

    - name: Upload release asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ matrix.asset_path }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/octet-stream
